FROM debian:stretch

ARG WGPUBLICKEY
ARG WGPRIVATEKEY

RUN echo "deb http://deb.debian.org/debian/ unstable main" > /etc/apt/sources.list.d/unstable-wireguard.list && \
 printf 'Package: *\nPin: release a=unstable\nPin-Priority: 90\n' > /etc/apt/preferences.d/limit-unstable

RUN apt-get update && \
 apt-get install -y --no-install-recommends wireguard-tools wget ca-certificates iptables net-tools procps openresolv && \
 apt-get clean

RUN wget https://dl.google.com/go/go1.15.2.linux-amd64.tar.gz && tar xf go1.15.2.linux-amd64.tar.gz && mv go /usr/local

RUN KVER=`uname -r`
RUN apt-get install -y linux-headers-$KVER && apt-get install -y --no-install-recommends wireguard-dkms bc

ENV GO111MODULE=on
ENV GOROOT=/usr/local/go
ENV GOPATH=/home/go
ENV PATH=$PATH:/usr/local/go/bin

WORKDIR /cloud-manager
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build ./cmd/agent/main.go && echo $WGPUBLICKEY > agent_pubKey && echo $WGPRIVATEKEY > agent_privKey
ENTRYPOINT ["./main"]
