FROM    golang:1.14.7-alpine3.12
ARG     WGPUBLICKEY
ARG     WGPRIVATEKEY
ENV     GO111MODULE=on
ENV     IPTABLES_MASQ=1
RUN     apk --no-cache add wireguard-tools iptables
WORKDIR /cloud-manager
COPY    go.mod .
COPY    go.sum .
RUN     go mod download
COPY    . .
RUN     go build ./cmd/agent/main.go && \
        echo $WGPUBLICKEY > agent_pubKey && echo $WGPRIVATEKEY > agent_privKey
ENTRYPOINT ["./main"]
