FROM    golang:1.15.2-alpine
ENV     GO111MODULE=on
WORKDIR /cloud-manager
COPY    go.mod .
COPY    go.sum .
RUN     go mod download
COPY    . .
RUN     go build ./cmd/manager/main.go
ENTRYPOINT ["./main"]
