hosts:
  - name: hawk-collector
    public_key: AAABBCC
    allowed_ips: 10.11.0.1/24
  - name: hawk-workers
    public_key: AAABBCC
    allowed_ips: 10.11.0.2/24
  - name: hawk-events
    public_key: AAABBCC
    allowed_ips: 10.11.0.3/24
  - name: hawk-collector
    public_key: AAABBCC
    allowed_ips: 10.11.0.4/24
  - name: hawk-api
    public_key: AAABBCC
    allowed_ips: 10.11.0.5/24
  - name: hawk-monitor
    public_key: AAABBCC
    allowed_ips: 10.11.0.6/24
  - name: hawk-gcp
    public_key: AAABBCC
    allowed_ips: 10.11.0.7/24

groups:
  - name: hawk-cloud1
    hosts:
      - hawk-collector
      - hawk-workers
      - hawk-events
      - hawk-api
  - name: hawk-eu
    hosts:
      - hawk-monitor
      - hawk-gcp